---
title: "About"
execute:
  warning: false
  message: false
---

This website presents an analysis of the predicted evolutionary response to selection in a population of _Drosophila melanogaster_. It accompanies the manuscript "The complication of sex: estimating adaptation when selection acts on females and males" in review at _Evolution_.

The [data collation](Data_collation.html) tab contains information on our dataset and documents how it was quality controlled. Our analysis relies on using the mean phenotypic values for near-isogenic lines of flies. Each line carries a single genotype so these phenotypic means can be used as estimates of breeding values.

The [Find line means](docs/Get_line_means_from_raw_data.html) tab documents the statistical modelling we used to find line means when only raw, individual level data was provided by the original study.

The [Analysis](docs/Main_analysis.html) tab documents our statistical analysis. It includes the code to wrangle the data, run the models and build the figures. 

We welcome any queries or comments concerning our analysis; please email `tkeaney@uni-mainz.de`

### Analysis system environment:

```{r, echo=FALSE}
library(tidyverse) # for tidy coding
library(MetBrewer) # for many nice colour palettes
library(rcartocolor) # more cool colours
library(kableExtra) # for scrolling tables
library(DT) # for interactive tables
library(patchwork) # to join multiple plots nicely
library(brms) # for bayesian models
library(tidybayes) # for more bayesian things
library(bayestestR) # for the pd metric 
library(broom) # convert results of functions into tables
library(ggtext) # for markdown features in ggplot
library(ggrepel) # for plot labels in ggplot
library(ggnewscale) # to reset scales in ggplot 
library(pander) # nice tables
library(groundhog) # to load package versions identical to ours

sessionInfo() %>% report::report()
```

